CREATE DATABASE IF NOT EXISTS DOCE_IMPACTO;

USE DOCE_IMPACTO;

CREATE TABLE IF NOT EXISTS USUARIOS(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL,
    TELEFONE BIGINT NOT NULL,
    SEXO VARCHAR(1),
    DATA_NASC DATE,
    CURSO_CARGO VARCHAR(100),
    TURNO VARCHAR(100),
    TIPO TINYINT NOT NULL,

    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS CAD_PRODUTO(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PRODUTO VARCHAR(100) NOT NULL,
    PRECO VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(100),
    CATEGORIA VARCHAR(100),
    IMAGEM LONGBLOB,
    PRIMARY KEY(ID)
);

SET character_set_client = utf8;
SET character_set_connection = utf8;
SET character_set_results = utf8;
SET collation_connection = utf8;

INSERT INTO USUARIOS(NOME, EMAIL, SENHA, TELEFONE, TIPO)
VALUES('ADM', 'ADM@EMAIL', 'SENHA123##', 99999, 0);

CREATE TABLE IF NOT EXISTS CARRINHO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT NOT NULL,  
    produto_id INT NOT NULL,  
    quantidade INT NOT NULL DEFAULT 1,
    FOREIGN KEY (produto_id) REFERENCES CAD_PRODUTO(id),
    FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id)
);

CREATE TABLE IF NOT EXISTS PEDIDO(
    ID_PEDIDO INTEGER AUTO_INCREMENT,
    ID_USUARIO INTEGER NOT NULL,
    TOTAL DECIMAL(12, 2) NOT NULL,
    STATUS_PEDIDO TINYINT NOT NULL DEFAULT 0,

    PRIMARY KEY(ID_PEDIDO)
);
